"""
Module for reading files generated by ASPECT or writing files used by ASPECT
"""
import re

def parse_parameters_to_dict(file_input):
    """
    Parse a deal.ii / ASPECT parameter file into a nested dictionary.

    This function reads a parameter file line-by-line and converts entries
    into a Python dictionary. Subsections are represented as nested dictionaries.
    It supports comments, multi-line values (ending with '\'), and repeated
    subsections which are merged.

    Parameters:
        file_input (TextIO):
            A file-like object opened for reading that contains deal.ii-style
            parameter content.

    Returns:
        dict:
            A dictionary where keys are parameter names or subsection names.
            Values are strings for parameters and dictionaries for subsections.
    """
    # Dictionary to store parsed parameters
    parameters = {}

    # Read the first line from the file
    current_line = file_input.readline()

    # Continue until end of file
    while current_line != "":
        # Supported input formats:
        # - Comments: lines starting with '#'
        # - Section markers: "subsection name" to start and "end" to close
        # - Key-value pairs: 'set key = value'

        if re.match(r'^(\t| )*#', current_line):
            # Skip comment lines
            pass

        elif re.match(r'^(\t| )*set', current_line):
            # Parse key-value pairs in 'set key = value' format

            # Remove the leading 'set' keyword
            line_cleaned = re.sub(r'^(\t| )*set ', '', current_line, count=1)

            # Split into key and value
            key_value_pair = line_cleaned.split('=', maxsplit=1)

            # Clean key formatting
            key = key_value_pair[0]
            key = re.sub(r'(\t| )*$', '', key)

            # Clean value formatting
            value = key_value_pair[1]
            value = re.sub(r'^ *', '', value)
            value = re.sub(r' *(#.*)?\n$', '', value)

            # Handle non-empty values
            if len(value) > 0:
                # Support multi-line values ending with '\'
                while value[-1] == '\\':
                    current_line = file_input.readline()
                    current_line = re.sub(r' *(#.*)?\n$', '', current_line)
                    value = value + '\n' + current_line

                # Store the parsed parameter
                parameters[key] = value

        elif re.match(r'^.*subsection', current_line):
            # Start of a subsection; create or update a nested dictionary

            # Extract subsection name
            subsection_name = re.sub(r'^.*subsection ', '', current_line)
            subsection_name = re.sub(r' *(#.*)?\n$', '', subsection_name)

            try:
                # If subsection already exists, prepare to update it
                parameters[subsection_name]
                print('%s is already presented, going to update.' % subsection_name)

            except KeyError:
                # Create new subsection recursively
                parameters[subsection_name] = parse_parameters_to_dict(file_input)

            else:
                # Merge new subsection entries into existing subsection
                new_entries = parse_parameters_to_dict(file_input)
                parameters[subsection_name].update(new_entries.items())

        elif re.match(r'^.*end', current_line):
            # End of current subsection: return parsed dictionary
            return parameters

        # Read the next line
        current_line = file_input.readline()

    return parameters


def save_parameters_from_dict(fout, parameters_dict, indent_level=0):
    """
    Write a nested parameter dictionary to a deal.ii / ASPECT formatted file.

    This function serializes a dictionary (including nested dictionaries)
    into deal.ii-style parameter syntax using 'set', 'subsection', and 'end'.

    Parameters:
        fout (TextIO):
            A writable file-like object where the formatted parameters
            will be written.

        parameters_dict (dict):
            Dictionary of parameters to write. Keys represent parameter names
            or subsection names. Values must be either:
            - str : for parameter values
            - dict : for nested subsections

        indent_level (int):
            The current indentation level used to format nested subsections.
            Each level corresponds to 4 spaces. Default is 0.

    Returns:
        None

    Raises:
        ValueError:
            If a value in the dictionary is not of type str or dict.
    """
    # Set indentation based on the current nesting level
    indent = ' ' * 4 * indent_level

    for key, value in parameters_dict.items():
        # Write parameter entries
        if isinstance(value, str):
            fout.write(indent + 'set %s = %s\n' % (key, value))

        # Write subsection entries recursively
        elif isinstance(value, dict):
            if indent_level == 0:
                fout.write('\n')

            fout.write(indent + 'subsection %s\n' % key)

            next_indent_level = indent_level + 1
            save_parameters_from_dict(fout, value, next_indent_level)

            fout.write(indent + 'end\n')

            if indent_level == 0:
                fout.write('\n')

        else:
            # Raise error for unsupported value types
            raise ValueError(
                'Value in dictionary must be str or dict, received:\n key: '
                + key
                + "\n type of value: "
                + str(type(value))
                + "\n value: "
                + str(value)
            )
